---
- hosts: all 
  become: true

  tasks:
    - name: Install  security updates
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop: 
        - openssl
        - openssh
      ignore_errors: yes
    - name: Check if doker is installed
      ansible.builtin.command: docker --version
      register: output
      ignore_errors: yes
    - ansible.builtin.debug:
        var: output
    - name: Install docker
      ansible.builtin.apt:
        name: docker.io 
        state: present
      when: output.failed
        
        
        